name: luma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Navigation & state
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1

  # Media / editing
  photo_manager: ^3.2.1
  image_cropper: ^8.0.2
  image: ^4.2.0
  vector_math: ^2.1.4

  # Monetization
  in_app_purchase: ^3.2.0

  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  
flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/branding/luma_app_icon_light.png
  remove_alpha_ios: true
  
flutter_native_splash:
  ios: true
  android: false
  web: false

  color: "#FFFFFF"
  color_dark: "#000000"

  image: assets/branding/wordmark.png
  branding: assets/branding/tagline.png

  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    # Editing assets
    - assets/grain.png

    # Branding
    - assets/branding/luma_app_icon_light.png
    - assets/branding/luma_app_icon_dark.png
    - assets/branding/wordmark.png
    - assets/branding/tagline.png
